//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escola.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Aluno
    {
        public int AlunoId { get; set; }
        [Display(Name = "Nome")]
        public string Nome { get; set; }
        [Display(Name = "Data de nascimento")]
        public System.DateTime DataNascimento { get; set; }
        [Display(Name = "Professor")]
        public int ProfessorId { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
